apiVersion: v1
kind: Service
metadata:
  name: locust-master
  labels:
    app: locust-master
spec:
  type: LoadBalancer
  ports:
    - port: 8089
      targetPort: 8089
      name: web-ui
  selector:
    app: locust-master
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: locust-master
  labels:
    app: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  serviceName: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      volumes:
        - name: locust-files
          emptyDir: {}
      containers:
        - name: locust-master
          image: "hahafree12/locust-on-k8s:git_sync"
          imagePullPolicy: Always
          ports:
            - containerPort: 8089
              name: web-ui
            - containerPort: 5557
              name: worker-port1
            - containerPort: 5558
              name: worker-port2
          env:
            - name: LOCUST_MODE
              value: master
          volumeMounts:
            - name: locust-files
              mountPath: "/locust"
        - name: git-sync
          image: "registry.k8s.io/git-sync/git-sync:v3.6.5"
          env:
            {{- with .Values.git_sync }}
            - name: GIT_SYNC_REPO
              value: {{ .repo }}
            - name: GIT_SYNC_BRANCH
              value: {{ .branch | default "main" }}
            {{- end }}
            - name: GIT_SYNC_USERNAME
              value: {{ .Values.git_username }}
            - name: GIT_SYNC_PASSWORD
              value: {{ .Values.git_password }}
            - name: GIT_SYNC_ROOT
              value: "/locust"
            - name: GIT_SYNC_DEST
              value: "my-locust-files"
          volumeMounts:
            - name: locust-files
              mountPath: "/locust"