apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  labels:
    app: locust-worker
spec:
  replicas: {{ .Values.worker_replicas | default 2 }}
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          image: "hahafree12/locust-on-k8s"
          ports:
            - containerPort: 5557
              name: worker-port1
            - containerPort: 5558
              name: worker-port2
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key
            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  name: locust-configmap
                  key: aws_default_region
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: locust-configmap
                  key: s3_bucket_name
            - name: S3_KEY
              valueFrom:
                configMapKeyRef:
                  name: locust-configmap
                  key: s3_object_key
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER_HOST
              value: locust-master-0.locust-master.default.svc.cluster.local