apiVersion: v1
kind: Service
metadata:
  name: locust-master
  labels:
    app: locust-master
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8089
      name: web-ui
  selector:
    app: locust-master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  labels:
    app: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
        - name: locust-master
          image: "hahafree12/locust-on-k8s"
          ports:
            - containerPort: 8089
              name: web-ui
            - containerPort: 5557
              name: worker-port1
            - containerPort: 5558
              name: worker-port2
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials-5tb8ctbmck
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials-5tb8ctbmck
                  key: aws_secret_access_key
            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  name: locust-configmap-kgk7m4h69d
                  key: aws_default_region
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: locust-configmap-kgk7m4h69d
                  key: s3_bucket_name
            - name: S3_KEY
              valueFrom:
                configMapKeyRef:
                  name: locust-configmap-kgk7m4h69d
                  key: s3_object_key
            - name: LOCUST_MODE
              value: master